### ISSUE TITLE
can't seem to find the URL

### ISSUE THREAD

**Issue by gyke69** [phatblat/WebView#3]
the default URL of the Xcode web view project is Apple.com how do I change that?

**Comment by phatblat** [comment]
Here's a simple example of loading a URL into the webview:

```swift
let url = URL(string: "https://github.com")!
let webViewStore = WebViewStore()
webViewStore.webView.load(URLRequest(url: url))
```

**Comment by gyke69** [comment]
> Here's a simply example of loading a URL into the webview:
> 
> ```swift
> let url = URL(string: "https://github.com")!
> let webViewStore = WebViewStore()
> webViewStore.webView.load(URLRequest(url: url))
> ```

I was looking into the wrong Direction, Thank you so much for this effective project, if there is a question I will definatly ask you.

**Comment by gyke69** [comment]
> Here's a simply example of loading a URL into the webview:
> 
> ```swift
> let url = URL(string: "https://github.com")!
> let webViewStore = WebViewStore()
> webViewStore.webView.load(URLRequest(url: url))
> ```


i added my website ,  but in order to install an application i have the following link to my plists, unfortunately your project doesn't give me the popup to install my app.  

href="itms-services://?action=download-manifest&url=https://yourwebsite/cdn/yourapp.plist

**Comment by phatblat** [comment]
`WKWebView` can't handle URLs like that. You'll need to pass it to `UIApplication.shared.openURL()`

**Comment by gyke69** [comment]
> `WKWebView` can't handle URLs like that. You'll need to pass it to `UIApplication.shared.openURL()`

Can I add 

UIApplication.shared.openURL()
To the WKWebView? Or it's not possible? If it is possible where do I add it?
